# Generated by Django 3.2.15 on 2022-09-23 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_image_upload_fvsf3n', upload_to='recipe-star-3-api/images/')),
                ('image_filter', models.CharField(choices=[('vegetables', 'vegetables'), ('eggs', 'eggs'), ('chicken', 'chicken'), ('pasta', 'pasta'), ('fish', 'fish'), ('bread', 'bread'), ('lamb', 'lamb'), ('fruit', 'fruit'), ('beef', 'beef'), ('cheese', 'cheese'), ('pork', 'pork'), ('rice', 'rice'), ('seafood', 'seafood'), ('goose', 'goose'), ('mussels', 'mussels'), ('chocolate', 'chocolate'), ('game', 'game'), ('duck', 'duck')], default='normal', max_length=32)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
