# Generated by Django 3.2.15 on 2022-09-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../recipe-star-3-api/default_user_profile_cmd66i', upload_to='recipe-star-3-api/images/'),
        ),
    ]
